// web/src/components/FormItem.vue
<script setup lang="ts">
interface Props {
  rules?: (value: string) => string | true;
}

const props = withDefaults(defineProps<Props>(), {
  rules: undefined,
});

const root = ref<HTMLElement>();
const validateError = ref('');

function validate() {
  if (!root.value) return;

  const input = root.value.getElementsByTagName('input').item(0);
  if (!input) {
    validateError.value = '';
    return;
  }

  if (props.rules) {
    const result = props.rules(input.value);
    validateError.value = result === true ? '' : `* ${result}`;
  } else {
    validateError.value = '';
  }
  input.setCustomValidity(validateError.value);
}
</script>

<template>
  <div class="relative w-auto">
    <div ref="root" class="flex" @input="validate" @blur="validate">
      <slot />
    </div>
    <div class="text-error mt-1 text-left text-xs text-red-600">
      {{ validateError }}
    </div>
  </div>
</template>

// web/src/components/FormItem.svelte
<script lang="ts">
  let { rules = undefined, children } = $props();

  let root: HTMLElement;
  let validateError = $state("");
  function validate() {
    const input = root.getElementsByTagName("input").item(0);
    if (!input) {
      validateError = "";
      return;
    }
    if (rules) {
      const result = rules(input.value);
      validateError = result === true ? "" : `* ${result}`;
    } else {
      validateError = "";
    }
    input.setCustomValidity(validateError);
  }
</script>

<div class="relative w-auto">
  <div class="flex" bind:this={root} oninput={validate} onblur={validate}>
    {@render children?.()}
  </div>
  <div class="text-error mt-1 text-left text-xs text-red-600">
    {validateError}
  </div>
</div>
